# Generated by Django 4.2.6 on 2023-12-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
    ]
